spring:
  application:
    name: backend

datasource:
  url: jdbc:mysql://localhost:3306/seeshow
  username: root
  password: your_password
  driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true